### ISSUE TITLE
Cannot load a long list with 70.000 entries

### ISSUE THREAD

**Issue by ioena07** [E3V3A/MMM-Tabulator#9]
**Expected Behaviour:**
Expected to see 20 items displayed on the mirror.

**Actual Behaviour:**
Instead of seeing the items, I see a message "Waiting for data". If I cut the list to 150 items (see attached file), it works as it should but if I expand it to 250 items (rows) then it doesn't work => "Waiting for data".
[ListaCuvinte.txt](https://github.com/E3V3A/MMM-Tabulator/files/2321649/ListaCuvinte.txt)
My girlfriend wants to learn Danish and I this is a list with all the Danish words, I want to make the mirror display 20 words at a time in DK, EN, RO and cycle through randomly every 3 min or so. 
I tried everything with this list but I don't seem to get it work. Any help would be very much appreciated.

**Steps to Reproduce the Issue:**
Please have a look at the attached file. It's saved as UTF-8 and all I did was to change the extension to JSON.  If you replace the demo.json with this one and change column names accordingly in the config files, it will not work (works with 150 words for example but not the rest). I don't know if it's an error in the file or the module cannot handle so much data.
Any input would be much appreciated.

---

For new bugs and issues, please **make sure** to:
- [ ] include detailed information on what you did before the *error/issue* occurred.
- [ ] get info about your system configuration, if relevant.
- [ ] make sure to **use code mark-down** using 3 backticks, ```, to enclose mulyi-line code/input/output.
- [ ] include a **screenshot!** for issues concerning *layouts, formatting*, or other UI stuff.

**Comment by E3V3A** [comment]
Hi @ioena07 !

Sorry for late response, but I've been away from MMM dev for a while. 
However, that is an interesting usage scenario! I see 3 things that may go wrong there:

1. The data is sent from the main MM module to the MMM-Tabulator module via some calls. These call were surely never meant to contain such large quantity of data. I think it could be very possible that MM & MMM-Tabulator simply choke on this. Perhaps try to write a script that only sends 20 at the time, so that you don't have to send 70,000*length! (You can't see the others anyway, right!?)

2. It's also possible it could be  RPi memory issue, when running many modules at the same time. Try turning off all other modules and see what happens.

3. It could also be a problem with the Tabulator library itself, in which case there is nothing I can do. File a report to their github site.

Thanks for reporting!

**Comment by E3V3A** [comment]
@ioena07 
Please report back in 15 days, or I will close this issue as invalid.
You can always re-open if you feel you have some new insights or solutions.

**Comment by ioena07** [comment]
Hi E3V3A,
Thank you for your answer. I think the sheer amount of data is chocking the Tabulator so a script would definitely make more sense but my knowledge of JavaScript is very limited. What I did instead was to use a similar module and display only one line at a time - it easier for the GF to memorize it. I am using the MMM-Tabulator to display some other things and it works perfectly so I will leave it like this for now. Thank you for taking the time to answer. 
BR
Ionut
